[package]
name = "dorion"
version = "0.5.0"
description = "Repackaged Discord Web Client"
authors = ["SpikeHD"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.6", features = ["api-all", "icon-ico", "system-tray"] }
# tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
dirs = { version = "5.0.1" }
reqwest = "0.11.14"
base64 = "0.13.0"

# For push to talk (and maybe other hotkeys in the future!)
device_query = "1.1.3"

sysinfo = { version = "0.26.8" }

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
webkit2gtk = "0.19.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc-foundation = "0.1"
cocoa = "0.24"

[target.'cfg(windows)'.dependencies]
webview2-com = "0.16.0"
windows-implement = "0.37.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.37.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
